### PR TITLE
CreateCharge can expand params

### PR DESCRIPTION
**Pull request by chreekat**
e.g. "balance_transaction" in the returned Charge.

### CODE REVIEW

**Comment by dmjio** [comment]
Thanks! I confirmed this with wayback machine docs. Don't mind CI, I'll fix that.

**Comment by chreekat** [comment]
Great! For my edification, can you explain what you mean about wayback machine? I see elsewhere you rely on it for API change info (heh), but I based this change on the most recent docs anyway.

**Comment by chreekat** [comment]
*as well as hitting the api with the patched version of the library

**Comment by dmjio** [comment]
I don't think the most recent docs reflect the 2014 API accurately (what this lib uses), so to find those docs, I use this: https://web.archive.org/web/20160706013943/https://stripe.com/docs/api#charge_object

**Comment by chreekat** [comment]
Oh snap, I forgot that *library internals* are where the API-version choice is made. :)

**Comment by dmjio** [comment]
Yea, I think it gets tricky in some cases. For example if you want to use web hooks (async notification ) for events, it will send you JSON in the format of whatever stripe version your console is at ( which would break our parsers if you're on a newer version ). But if you retrieve events ( synchronous polling ) and have your API version specified in the header, it will return things correctly, according to the API version in this lib. The struggle is real.

**Pull request merged**
