### PR TITLE
Bump aeson upper bound to 1.1.*

### PR DESCRIPTION
**Pull request by WillSewell**
This makes it compatible with the latest stackage nightly (`nightly-2016-10-26`).

### CODE REVIEW

**Comment by dmjio** [comment]
@WillSewell, 

Can you explicitly avoid `aeson` version `0.10.0.0`.

```bash
>= 0.8  && < 0.10 || >= 0.11 && < 1.2
```

I'd commit a change with the above (test first if you could), then rebase off master, and fixup/squash the last commit.

**Comment by dmjio** [comment]
@WillSewell, Oh, and thanks :)

**Comment by dmjio** [comment]
There's probably quite a few deps. that need to be upgraded.

**Comment by WillSewell** [comment]
No problem @dmjio. Just checking if you did mean `>= 0.8  && < 0.10 || >= 0.11 && < 1.2` and not `>= 0.8  && < 0.10 || >= 0.11 && < 1.1`? Since `1.1.*` hasn't been released yet.

**Comment by WillSewell** [comment]
I guess the title is misleading. It's a *non inclusive* upper bound. Oops.

**Comment by dmjio** [comment]
@WillSewell, ah yes, that's what I meant :)

**Comment by dmjio** [comment]
Thought 1.1 was latest for some reason

**Comment by WillSewell** [comment]
Ok, updated :)

**Comment by dmjio** [comment]
@WillSewell, awesome, thanks :) Don't worry about the CI, I'll fix that.

**Pull request merged**
