### PR TITLE
Clean up default.nix

### PR DESCRIPTION
**Pull request by 3noch**
I haven't actually tested this yet...but this file needed some work.

### CODE REVIEW

**Comment by dmjio** [comment]
Ah, thanks for this reminder, this code is actually removing all of haskell packages.
It should really merging the attribute sets.
```nix
let config = {
  packageOverrides = pkgs: { 
     haskell = pkgs.haskell // { 
       packages = pkgs.haskell.packages // { 
          ${compiler} = pkgs.haskell.packages.${compiler}.override { 
               overrides = self: super: { 
                   # ....
              };
          };
       };
    };
 };
```

**Comment by dmjio** [comment]
Removing `doCheck = args.pname == "stripe-http-streams";` forces tests to run for all dependencies.

**Comment by 3noch** [comment]
Ah I didn't realize you didn't want to run tests on any dependencies.

**Comment by dmjio** [comment]
Sometimes travis times out, since it takes a long time.

**Comment by dmjio** [comment]
It seems like modifying the derivation won't allow us to use the binary cache, since the hashes are now different, so maybe this PR will actually make builds faster. Since my `doCheck = args.pname == "stripe-http-streams";` altered the hash.

**Comment by 3noch** [comment]
I did think of that. The last time I tried overriding `mkDerivation` it invalidated the cache. But I haven't tried here.

**Comment by 3noch** [comment]
But even my patch still modifies `mkDerivation`.

**Comment by dmjio** [comment]
Ah, if you change `haddock ? false` to `true` it will probably be the same.

**Comment by dmjio** [comment]
fixed in https://github.com/dmjio/stripe/commit/b3f7bd80bcca0f8ecf0bd9e1fd4b74e68dce3dfb#diff-5712e736e0de6ba170577f8472c398e9

**Pull request closed without merging**
