### PR TITLE
Retrieve all subscriptions

### LINKED ISSUE #83: Retrieving all subscriptions
The Stripe API allows [retrieving _all_ subscriptions](https://stripe.com/docs/api/curl#list_subscriptions), _i.e._ not only those associated with a particular customer ID. However the `stripe-haskell` library only allows retrieving subscriptions by customer ID:

https://github.com/dmjio/stripe/blob/master/stripe-core/src/Web/Stripe/Subscription.hs#L189

I've created a fork where I can retrieve all the subscriptions: https://github.com/dmjio/stripe/compare/master...nmattia:nm/retrieve-all-subsc

While this works (and passes the tests), and while another function could be written to retrieve subscriptions by customer ID (`getCustomerSubscriptions`), this is unfortunately a breaking change. Let me know if you see a nice (or at least acceptable) way of introducing the API call and I'll happily submit a PR.

### PR DESCRIPTION
**Pull request by nmattia**
This renames the current `getSubscriptions` to `getSubscriptionsByCustomerId` and introduces a new `getSubscriptions`:

``` haskell
-- | Retrieve all active `Subscription`s
getSubscriptions
    :: StripeRequest GetSubscriptions
```

which retrieves all the subscriptions (for all customers). 
Fixes #83

### CODE REVIEW

**Comment by dmjio** [comment]
@nmattia Thanks 🍻 !

**Comment by dmjio** [comment]
@nmattia your changes are live on `2.3.0`, if there's anything else you need, don't hesitate to ask.

**Comment by dmjio** [comment]
@nmattia thanks for using it 👍

**Comment by nmattia** [comment]
Ah, I actually came up with some items (since you asked :) )

* https://github.com/dmjio/stripe/issues/90
* https://github.com/dmjio/stripe/issues/89

Will be happy to pay in :beers: if you swing by https://zurihac.info/

**Comment by dmjio** [comment]
:) I unfortunately won't be at ZuriHac, but I do accept payment in other forms as well :)

**Pull request merged**
